import { Link } from "@/i18n/routing";
import { ArrowUpRight } from "lucide-react";
import Footer from "@/components/blocks/Footer";
import SiteLogoText from "@/components/typography/SiteLogoText";
import PageTitle from "@/components/typography/PageTitle";
import PageSubtitle from "@/components/typography/PageSubtitle";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

const AboutPage = () => {
  return (
    <div className="w-full flex flex-col items-center justify-center px-4 lg:px-8 py-4">
      <div className="w-full max-w-6xl">
        <SiteLogoText variant="small" includeSecondaryText />
      </div>
      <div className="w-full pt-4 pb-2 px-4 lg:px-8">
        <PageTitle text="About" />
      </div>
      <div className="w-full h-full flex flex-col items-center justify-center gap-4">
        <Card className="w-full max-w-6xl">
          <CardHeader>
            <PageSubtitle text="JudgeGPT - Evaluating AI-Generated News Authenticity" />
          </CardHeader>
          <CardContent className="w-full">
            <p className="font-light w-full">
              JudgeGPT is a research project focused on critically evaluating
              news content generated by AI, exploring the nuanced perceptions of
              authenticity in machine-generated vs. human-generated news. This
              pioneering work aims to gather insights on how individuals discern
              between real and artificial news content in an era of rapidly
              advancing language models. 🔍 Want to test your judgment? If
              you're interested in seeing this application in action and would
              like to participate in the evaluation of fake news, please visit
              our interactive survey at https://judgegpt.streamlit.app/. A port
              to React is currently in development, and can be beta tested at
              https://aka.ms/JudgeGPT. 🧠 Curious about spotting fake news? If
              you want to learn more about spotting fake news, especially during
              election periods, check out this blog post for tips and insights.
            </p>
          </CardContent>
        </Card>
        <Card className="w-full max-w-6xl">
          <CardHeader>
            <PageSubtitle text="Disclaimer" />
          </CardHeader>
          <CardContent className="w-full">
            <p className="font-light w-full">
              JudgeGPT is an independent research project and is not affiliated
              with, endorsed by, or in any way officially connected to OpenAI.
              The use of "GPT" within our project name is purely for descriptive
              purposes, indicating the use of generative pre-trained transformer
              models as a core technology in our research. Our project's
              explorations and findings are our own and do not reflect the views
              or positions of OpenAI or its collaborators. We are committed to
              responsible AI research and adhere to ethical guidelines in all
              aspects of our work, including the generation and analysis of
              content.
            </p>
          </CardContent>
        </Card>
        <Card className="w-full max-w-6xl">
          <CardHeader>
            <PageSubtitle text="More Info" />
          </CardHeader>
          <CardContent className="w-full">
            <span className="font-light w-full flex gap-2">
              GitHub Repository:
              <a
                href="https://github.com/Shreyasdbz/judge-gpt-quiz-fe"
                target="blank"
                className="text-accent-foreground font-medium"
              >
                Github
              </a>
            </span>
          </CardContent>
        </Card>
      </div>

      <Link href={"/home"} className="my-8">
        <Button variant="secondary" className="gap-2">
          <span>Back to Home</span>
          <ArrowUpRight size={16} />
        </Button>
      </Link>

      <div className="w-full max-w-6xl">
        <Footer variant="bottom" />
      </div>
    </div>
  );
};

export default AboutPage;
